# Additional needed when frontend fixed
version: "3.0"
services:
  db:
    name: mongo
    image: "mongo:latest"
    volume:
      - "/var/mongo:/data/db"
  backend:
    name: flask
    build: Backend/.
    ports:
      - "5000:5000"